//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWithTokenAuthen.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refresh_Token
    {
        public string Refresh_Token_Id { get; set; }
        public string Refresh_Token1 { get; set; }
        public string Username { get; set; }
        public System.DateTime Issued_At_Utc { get; set; }
        public System.DateTime Expired_At_Utc { get; set; }
    }
}
